language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service acpid stop
  - sudo service atd stop
  - sudo service cron stop
  - sudo service memcached stop
  - sudo service ntp stop
  - sudo service rabbitmq-server stop
  - sudo service resolvconf stop
  - sudo service sshguard stop
  - sudo service ssh stop
  - sudo service rsyslog stop
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then openssl aes-256-cbc -K $encrypted_68e41c8904c9_key -iv $encrypted_68e41c8904c9_iv -in settings.tar.enc -out settings.tar -d && tar -xf settings.tar && cat known_hosts >> ~/.ssh/known_hosts ; fi

install: mvn install -Dcargo.maven.skip -Ddocker.skip -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn -s ./settings.xml deploy -Dexternal -DtrimStackTrace=false ; else mvn verify -DtrimStackTrace=false ; fi

after_failure: for testdir in `find . -name surefire-reports -o -name failsafe-reports` ; do cat ${testdir}/*.txt ; done