version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    env_file: .env
    environment:
      ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_CLIENT_PORT}"
      ZOOKEEPER_TICK_TIME: "${ZOOKEEPER_TICK_TIME}"
    ports: 
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    env_file: .env
    environment:
      KAFKA_BROKER_ID: "${KAFKA_BROKER_ID}"
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      KAFKA_ADVERTISED_LISTENERS: "${KAFKA_ADVERTISED_LISTENERS}"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}"
    ports:
      - "${RMAP_KAFKA_PORT}:${RMAP_KAFKA_PORT}"

  solrindexing:
     container_name: solrindexing
     image: solr:6.6.0-alpine
     user: root
     env_file: .env
     ports:
       - "${SOLR_PORT}:${SOLR_PORT}"
       - "${SOLR_DEBUG_PORT}:${SOLR_DEBUG_PORT}"
     volumes:
       - "./cores:/opt/solr/server/solr/mycores"
     entrypoint:
       - docker-entrypoint.sh
       - solr
       - start
       - -f
       - -force
       - -a
       - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${SOLR_DEBUG_PORT}"
